package com.toroidalworld.compat.c2me;

import org.jspecify.annotations.Nullable;

import com.toroidalworld.noise.GenerationTransformerContext;
import com.toroidalworld.noise.GenerationTransformerContext.Context;

import net.minecraft.world.level.levelgen.DensityFunction;

// The runtime half of the compiled fold: the two calls C2meDfc's generated bytecode makes, and the only place the
// compiled noise path meets this mod.
//
// Split in two on purpose. The compiled method must decide which of its two input trees to evaluate before it
// evaluates either — the folded tree hands the noise raw block coordinates, the vanilla one hands it coordinates
// already scaled and shifted — so the question "is this generation wrapped" is asked first, on its own, and the answer
// is carried into the sample rather than asked again. One thread-local lookup per noise node, which is exactly what
// DensityFunctions$Noise.compute pays on a world C2ME is not compiling.
public final class C2meDfcFold {
    // The context only when this thread is bound to a wrapping generation, else null — the compiled branch reads it as
    // a null check. Deliberately not "is the level wrapped": an unbound thread must take the vanilla branch, because
    // the folded one would hand ImprovedNoise a raw coordinate that no longer has a scale coming to meet it.
    public static @Nullable Context wrappedContext() {
        Context context = GenerationTransformerContext.context();
        return context.transformer().isWrapped() ? context : null;
    }

    // The sample C2ME's InvocationShim would have made, with the horizontal scale parked around it instead of baked
    // into X and Z. The scale reaches the lattice through the context and becomes its period there; the coordinates
    // arrive raw so the fold can close them on the world circle.
    public static double sample(Context context, DensityFunction.NoiseHolder noise,
            double x, double y, double z, double horizontalScale) {
        try (Context.ScaleScope _ = context.withScale(horizontalScale)) {
            return noise.getValue(x, y, z);
        }
    }

    private C2meDfcFold() {
    }
}
